/*------------------------------------------
   SVG.CPP -- SVG File Write Functions
  ------------------------------------------*/

#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <vector>
#include "manpwin.h"
#include "Dib.h"
#include "colour.h"
#include "OtherFunctions.h"
#include "Hailstone.h"

extern	CDib		Dib;
extern	CTrueCol	TrueCol;
extern	int		xdots, ydots;
extern	long		threshold;
extern	double		hor, vert, mandel_width;
extern	char		*FractData(void);
extern	WORD		type;
extern	int		subtype;
extern	double		param[];
extern	double		iterations;
extern  COtherFunctions* g_pOtherFunctions;

/**************************************************************************
	Write SVG File with Metadata
	Based on the format from Numerical Visualizations
**************************************************************************/

int	write_svg_file(HWND hwnd, char *outfile, char *szAppName, char *CommentText)
{
    FILE	*fp = NULL;
    char	s[480];
    time_t	current_time;
    struct tm	*time_info;
    char	time_buffer[80];
    static HCURSOR	hCursor;
    BYTE	*pixels;
    int		x, y;
    RGBTRIPLE	rgb;

    hCursor = LoadCursor((HINSTANCE)NULL, IDC_WAIT);
    SetCursor(hCursor);

    // Open file for writing
    if ((fp = fopen(outfile, "w")) == NULL)
    {
        hCursor = LoadCursor((HINSTANCE)NULL, IDC_ARROW);
        SetCursor(hCursor);
        wsprintf(s, "SVG can't open output file: %s", outfile);
        MessageBox(hwnd, s, szAppName, MB_ICONEXCLAMATION | MB_OK);
        MessageBeep(0);
        return -1;
    }

    // Get current time for metadata
    time(&current_time);
    time_info = localtime(&current_time);
    strftime(time_buffer, sizeof(time_buffer), "%Y-%m-%dT%H:%M:%S", time_info);

    // Write SVG header with viewBox in pixel coordinates
    // Using viewBox with preserveAspectRatio for responsive scaling
    // The viewBox defines the coordinate system (pixels), while the SVG scales to fit
    fprintf(fp, "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n");
    fprintf(fp, "<svg viewBox=\"0 0 %d %d\"\n", xdots, ydots);
    fprintf(fp, "     preserveAspectRatio=\"xMidYMid meet\"\n");
    fprintf(fp, "     style=\"max-width: 100%%; height: auto;\"\n");
    fprintf(fp, "     xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\">\n");
    fprintf(fp, "  <!-- ========================================= -->\n");
    fprintf(fp, "  <!-- ManpWIN Metadata                         -->\n");
    fprintf(fp, "  <!-- ========================================= -->\n");
    fprintf(fp, "  <title>Hailstone Sequence Visualization</title>\n");
    fprintf(fp, "  <desc>2D visualization of Collatz-inspired dynamics generated by ManpWIN</desc>\n");
    fprintf(fp, "\n");

    // Write RDF metadata
    fprintf(fp, "  <metadata>\n");
    fprintf(fp, "    <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n");
    fprintf(fp, "             xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n");
    fprintf(fp, "      <rdf:Description>\n");
    fprintf(fp, "        <dc:title>Hailstone Sequence Visualization</dc:title>\n");
    fprintf(fp, "        <dc:creator>ManpWIN64</dc:creator>\n");
    fprintf(fp, "        <dc:date>%s</dc:date>\n", time_buffer);
    fprintf(fp, "        <dc:format>image/svg+xml</dc:format>\n");
    fprintf(fp, "        <dc:description>Exported from ManpWIN fractal application</dc:description>\n");
    fprintf(fp, "      </rdf:Description>\n");
    fprintf(fp, "    </rdf:RDF>\n");
    fprintf(fp, "  </metadata>\n");
    fprintf(fp, "\n");

    // Write application-specific metadata
    fprintf(fp, "  <!-- Application-Specific Metadata for Reproducibility -->\n");
    fprintf(fp, "  <g id=\"visualization-parameters\" style=\"display:none;\">\n");
    fprintf(fp, "    <desc>\n");
    fprintf(fp, "      Visualization Type: Hailstone Sequence\n");
    fprintf(fp, "      Software: ManpWIN64\n");
    fprintf(fp, "      Export Date: %s\n", time_buffer);
    fprintf(fp, "      Resolution: %dx%d pixels\n", xdots, ydots);
    fprintf(fp, "\n");
    fprintf(fp, "      Algorithm Parameters:\n");
    fprintf(fp, "        MaxIterations: %ld\n", iterations);
    fprintf(fp, "        Type: %d\n", type);
    fprintf(fp, "        Subtype: %d\n", subtype);
    
    // Write parameters if available
    fprintf(fp, "        Parameters:\n");
    for (int i = 0; i < 10; i++)
    {
        if (param[i] != 0.0)
            fprintf(fp, "          param[%d]: %.10g\n", i, param[i]);
    }
    fprintf(fp, "\n");
    
    fprintf(fp, "      Color Mapping:\n");
    fprintf(fp, "        Palette: %ld colors\n", threshold);
    fprintf(fp, "        Method: Iteration-based coloring\n");
    fprintf(fp, "\n");
    
    fprintf(fp, "      Coordinate System:\n");
    fprintf(fp, "        Center X: %.10g\n", hor);
    fprintf(fp, "        Center Y: %.10g\n", vert);
    fprintf(fp, "        Width: %.10g\n", mandel_width);
    fprintf(fp, "\n");
    fprintf(fp, "      ViewBox (pixel coordinates for SVG rendering):\n");
    fprintf(fp, "        minX: 0\n");
    fprintf(fp, "        minY: 0\n");
    fprintf(fp, "        width: %d\n", xdots);
    fprintf(fp, "        height: %d\n", ydots);

    // Add Hailstone-specific information if this is a Hailstone fractal
    if (type == 245) // HAILSTONE
    {
        if (g_pOtherFunctions && g_pOtherFunctions->pHailstone)
        {
            const HailstoneConfig& config = g_pOtherFunctions->pHailstone->GetConfig();
            const CycleInfo& cycleInfo = g_pOtherFunctions->pHailstone->GetCycleInfo();
            const std::vector<HailstonePoint>& points = g_pOtherFunctions->pHailstone->GetPoints();

            fprintf(fp, "\n");
            fprintf(fp, "      Hailstone Sequence Information:\n");
            fprintf(fp, "        Starting Point: (%d, %d)\n", config.startX, config.startY);
            fprintf(fp, "        Total Iterations: %d\n", (int)points.size());
            fprintf(fp, "        Max Iterations: %d\n", config.maxIterations);

            if (cycleInfo.detected)
            {
                fprintf(fp, "        Cycle Detected: YES\n");
                fprintf(fp, "          Cycle Point: (%d, %d)\n", cycleInfo.x, cycleInfo.y);
                fprintf(fp, "          First Seen: Step %d\n", cycleInfo.startStep);
                fprintf(fp, "          Repeated At: Step %d\n", cycleInfo.endStep);
                fprintf(fp, "          Cycle Length: %d\n", cycleInfo.length);
            }
            else
            {
                fprintf(fp, "        Cycle Detected: NO (stopped at max iterations)\n");
            }

            fprintf(fp, "        Display Options:\n");
            fprintf(fp, "          Show Axes: %s\n", config.showAxes ? "Yes" : "No");
            fprintf(fp, "          Show Point Labels: %s\n", config.showPointLabels ? "Yes" : "No");
            fprintf(fp, "          Show Dots: %s\n", config.showDots ? "Yes" : "No");
        }
    }

    fprintf(fp, "    </desc>\n");
    fprintf(fp, "  </g>\n");
    fprintf(fp, "\n");

    // Write visualization graphics
    fprintf(fp, "  <!-- Visualization Graphics -->\n");
    fprintf(fp, "  <rect width=\"100%%\" height=\"100%%\" fill=\"black\"/>\n");
    fprintf(fp, "\n");

    // Get pixel data from DIB and write as SVG
    pixels = Dib.DibPixels.data();
    if (pixels != NULL)
    {
        // Write pixels as small rectangles
        // For performance, we could group consecutive pixels of the same color
        for (y = 0; y < ydots; y++)
        {
            for (x = 0; x < xdots; x++)
            {
                int offset = (y * xdots + x);
                BYTE colorIndex = pixels[offset];

                // Get RGB color from palette
                if (colorIndex < threshold && colorIndex < MAXPALETTE)
                {
                    rgb = TrueCol.PalettePtr[colorIndex];

                    // Only write non-black pixels to keep file size reasonable
                    if (rgb.rgbtRed != 0 || rgb.rgbtGreen != 0 || rgb.rgbtBlue != 0)
                    {
                        fprintf(fp, "  <rect x=\"%d\" y=\"%d\" width=\"1\" height=\"1\" fill=\"rgb(%d,%d,%d)\"/>\n",
                                x, y, rgb.rgbtRed, rgb.rgbtGreen, rgb.rgbtBlue);
                    }
                }
            }
        }
    }

    // Close SVG
    fprintf(fp, "</svg>\n");
    fclose(fp);

    hCursor = LoadCursor((HINSTANCE)NULL, IDC_ARROW);
    SetCursor(hCursor);

    return 0;
}
